
name: build

on:
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python "3.10.14"
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.14"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # gooey has extra dependencies not installed by pip so skip gooey
        #pip install numpy h5py matplotlib scipy tqdm
        pip install .
    - name: Build a binary wheel and a source tarball
      run: |
        pip install build
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      #uses: pypa/gh-action-pypi-publish@main
      #with:
      #  password: ${{ secrets.PYPI_API_TOKEN }}
